export const techStack = [
  { title: 'Languages', stack: ['Javascript', 'HTML', 'CSS'] },
  {
    title: 'Libraries',
    stack: [
      'Node',
      'Express',
      'React',
      'Redux',
      'Mocha',
      'Chai',
      'Jasmine',
      'Jest',
      'Leaflet',
      'Passport',
      'Viro React',
      'React Native',
      'Gatsby',
      'Victory',
      'Socket.io',
    ],
  },
  {
    title: 'Tools',
    stack: [
      'Git',
      'Github',
      'PostgreSQL',
      'Sequelize',
      'Heroku',
      'Travis-CI',
      'Netflify',
      'Postman',
      'Postico',
      'Firebase',
      'AWS',
      'Google OAuth',
      'Webpack',
      'Babel',
    ],
  },
]
